FROM ruby:3.4.5

RUN apt-get update -qq && \
    apt-get install -y build-essential nodejs npm postgresql-client && \
    npm install -g yarn
    

WORKDIR /myapp

COPY Gemfile ./
RUN bundle install

# ここではコードをコピーしない（docker-composeで同期するため）

CMD ["rails", "server", "-b", "0.0.0.0"]